/// Details resolved from an Indian Postal PIN code.
class PinCodeInfo {
  final String pinCode;
  final bool isValid;
  final String? state;
  final String? district;
  final String? zone;
  final String? circle;
  final bool isArmyPostal;

  const PinCodeInfo({
    required this.pinCode,
    required this.isValid,
    this.state,
    this.district,
    this.zone,
    this.circle,
    this.isArmyPostal = false,
  });

  @override
  String toString() {
    return 'PinCodeInfo(pin: $pinCode, valid: $isValid, state: $state, district: $district, zone: $zone)';
  }
}

/// Offline lookup tables for Indian PIN codes.
class BharatPinCodeData {
  static const Map<String, String> zones = {
    '1': 'Northern Postal Zone (Delhi, Haryana, Punjab, HP, J&K, Ladakh, Chandigarh)',
    '2': 'Northern Postal Zone (Uttar Pradesh, Uttarakhand)',
    '3': 'Western Postal Zone (Rajasthan, Gujarat, Daman & Diu, DNH)',
    '4': 'Western Postal Zone (Maharashtra, Goa, MP, Chhattisgarh)',
    '5': 'Southern Postal Zone (Andhra Pradesh, Telangana, Karnataka)',
    '6': 'Southern Postal Zone (Tamil Nadu, Kerala, Puducherry, Lakshadweep)',
    '7': 'Eastern Postal Zone (West Bengal, Odisha, North-East, Andaman & Nicobar)',
    '8': 'Eastern Postal Zone (Bihar, Jharkhand)',
    '9': 'Army Postal Service (APS)',
  };

  /// 2-digit Circle prefix to default State / Union Territory mapping.
  static const Map<String, Map<String, String>> circleData = {
    '11': {'state': 'Delhi', 'circle': 'Delhi'},
    '12': {'state': 'Haryana', 'circle': 'Haryana'},
    '13': {'state': 'Haryana', 'circle': 'Haryana'},
    '14': {'state': 'Punjab', 'circle': 'Punjab'},
    '15': {'state': 'Punjab', 'circle': 'Punjab'},
    '16': {'state': 'Chandigarh', 'circle': 'Punjab'},
    '17': {'state': 'Himachal Pradesh', 'circle': 'Himachal Pradesh'},
    '18': {'state': 'Jammu & Kashmir', 'circle': 'J&K'},
    '19': {'state': 'Jammu & Kashmir', 'circle': 'J&K'},
    '20': {'state': 'Uttar Pradesh', 'circle': 'Uttar Pradesh'},
    '21': {'state': 'Uttar Pradesh', 'circle': 'Uttar Pradesh'},
    '22': {'state': 'Uttar Pradesh', 'circle': 'Uttar Pradesh'},
    '23': {'state': 'Uttar Pradesh', 'circle': 'Uttar Pradesh'},
    '24': {'state': 'Uttar Pradesh', 'circle': 'Uttar Pradesh'},
    '25': {'state': 'Uttar Pradesh', 'circle': 'Uttar Pradesh'},
    '26': {'state': 'Uttarakhand', 'circle': 'Uttarakhand'},
    '27': {'state': 'Uttar Pradesh', 'circle': 'Uttar Pradesh'},
    '28': {'state': 'Uttar Pradesh', 'circle': 'Uttar Pradesh'},
    '30': {'state': 'Rajasthan', 'circle': 'Rajasthan'},
    '31': {'state': 'Rajasthan', 'circle': 'Rajasthan'},
    '32': {'state': 'Rajasthan', 'circle': 'Rajasthan'},
    '33': {'state': 'Rajasthan', 'circle': 'Rajasthan'},
    '34': {'state': 'Rajasthan', 'circle': 'Rajasthan'},
    '36': {'state': 'Gujarat', 'circle': 'Gujarat'},
    '37': {'state': 'Gujarat', 'circle': 'Gujarat'},
    '38': {'state': 'Gujarat', 'circle': 'Gujarat'},
    '39': {'state': 'Gujarat', 'circle': 'Gujarat'},
    '40': {'state': 'Maharashtra', 'circle': 'Maharashtra'},
    '41': {'state': 'Maharashtra', 'circle': 'Maharashtra'},
    '42': {'state': 'Maharashtra', 'circle': 'Maharashtra'},
    '43': {'state': 'Maharashtra', 'circle': 'Maharashtra'},
    '44': {'state': 'Maharashtra', 'circle': 'Maharashtra'},
    '45': {'state': 'Madhya Pradesh', 'circle': 'Madhya Pradesh'},
    '46': {'state': 'Madhya Pradesh', 'circle': 'Madhya Pradesh'},
    '47': {'state': 'Madhya Pradesh', 'circle': 'Madhya Pradesh'},
    '48': {'state': 'Madhya Pradesh', 'circle': 'Madhya Pradesh'},
    '49': {'state': 'Chhattisgarh', 'circle': 'Chhattisgarh'},
    '50': {'state': 'Telangana', 'circle': 'Telangana'},
    '51': {'state': 'Andhra Pradesh', 'circle': 'Andhra Pradesh'},
    '52': {'state': 'Andhra Pradesh', 'circle': 'Andhra Pradesh'},
    '53': {'state': 'Andhra Pradesh', 'circle': 'Andhra Pradesh'},
    '56': {'state': 'Karnataka', 'circle': 'Karnataka'},
    '57': {'state': 'Karnataka', 'circle': 'Karnataka'},
    '58': {'state': 'Karnataka', 'circle': 'Karnataka'},
    '59': {'state': 'Karnataka', 'circle': 'Karnataka'},
    '60': {'state': 'Tamil Nadu', 'circle': 'Tamil Nadu'},
    '61': {'state': 'Tamil Nadu', 'circle': 'Tamil Nadu'},
    '62': {'state': 'Tamil Nadu', 'circle': 'Tamil Nadu'},
    '63': {'state': 'Tamil Nadu', 'circle': 'Tamil Nadu'},
    '64': {'state': 'Tamil Nadu', 'circle': 'Tamil Nadu'},
    '67': {'state': 'Kerala', 'circle': 'Kerala'},
    '68': {'state': 'Kerala', 'circle': 'Kerala'},
    '69': {'state': 'Kerala', 'circle': 'Kerala'},
    '70': {'state': 'West Bengal', 'circle': 'West Bengal'},
    '71': {'state': 'West Bengal', 'circle': 'West Bengal'},
    '72': {'state': 'West Bengal', 'circle': 'West Bengal'},
    '73': {'state': 'West Bengal', 'circle': 'West Bengal'},
    '74': {'state': 'West Bengal', 'circle': 'West Bengal'},
    '75': {'state': 'Odisha', 'circle': 'Odisha'},
    '76': {'state': 'Odisha', 'circle': 'Odisha'},
    '77': {'state': 'Odisha', 'circle': 'Odisha'},
    '78': {'state': 'Assam', 'circle': 'Assam'},
    '79': {'state': 'North Eastern', 'circle': 'North East'},
    '80': {'state': 'Bihar', 'circle': 'Bihar'},
    '81': {'state': 'Bihar', 'circle': 'Bihar'},
    '82': {'state': 'Jharkhand', 'circle': 'Jharkhand'},
    '83': {'state': 'Jharkhand', 'circle': 'Jharkhand'},
    '84': {'state': 'Bihar', 'circle': 'Bihar'},
    '85': {'state': 'Bihar', 'circle': 'Bihar'},
    '90': {'state': 'Army Postal Service', 'circle': 'APS'},
    '91': {'state': 'Army Postal Service', 'circle': 'APS'},
    '92': {'state': 'Army Postal Service', 'circle': 'APS'},
    '93': {'state': 'Army Postal Service', 'circle': 'APS'},
    '94': {'state': 'Army Postal Service', 'circle': 'APS'},
    '95': {'state': 'Army Postal Service', 'circle': 'APS'},
    '96': {'state': 'Army Postal Service', 'circle': 'APS'},
    '97': {'state': 'Army Postal Service', 'circle': 'APS'},
    '98': {'state': 'Army Postal Service', 'circle': 'APS'},
    '99': {'state': 'Army Postal Service', 'circle': 'APS'},
  };

  /// 3-digit prefix mapping to Sorting District and specific State/UT.
  static const Map<String, Map<String, String>> districtData = {
    // Delhi
    '110': {'district': 'New Delhi / Central Delhi', 'state': 'Delhi'},

    // Haryana
    '121': {'district': 'Faridabad', 'state': 'Haryana'},
    '122': {'district': 'Gurugram', 'state': 'Haryana'},
    '123': {'district': 'Rewari', 'state': 'Haryana'},
    '124': {'district': 'Rohtak', 'state': 'Haryana'},
    '125': {'district': 'Hisar', 'state': 'Haryana'},
    '126': {'district': 'Jind', 'state': 'Haryana'},
    '127': {'district': 'Bhiwani', 'state': 'Haryana'},
    '131': {'district': 'Sonipat', 'state': 'Haryana'},
    '132': {'district': 'Panipat / Karnal', 'state': 'Haryana'},
    '133': {'district': 'Ambala', 'state': 'Haryana'},
    '134': {'district': 'Panchkula', 'state': 'Haryana'},
    '135': {'district': 'Yamunanagar', 'state': 'Haryana'},
    '136': {'district': 'Kurukshetra', 'state': 'Haryana'},

    // Punjab & Chandigarh
    '140': {'district': 'SAS Nagar (Mohali) / Ropar', 'state': 'Punjab'},
    '141': {'district': 'Ludhiana', 'state': 'Punjab'},
    '142': {'district': 'Moga', 'state': 'Punjab'},
    '143': {'district': 'Amritsar', 'state': 'Punjab'},
    '144': {'district': 'Jalandhar', 'state': 'Punjab'},
    '145': {'district': 'Pathankot', 'state': 'Punjab'},
    '146': {'district': 'Hoshiarpur', 'state': 'Punjab'},
    '147': {'district': 'Patiala', 'state': 'Punjab'},
    '148': {'district': 'Sangrur', 'state': 'Punjab'},
    '151': {'district': 'Bathinda', 'state': 'Punjab'},
    '152': {'district': 'Firozpur', 'state': 'Punjab'},
    '160': {'district': 'Chandigarh', 'state': 'Chandigarh'},

    // Himachal Pradesh
    '171': {'district': 'Shimla', 'state': 'Himachal Pradesh'},
    '172': {'district': 'Solan / Kinnaur', 'state': 'Himachal Pradesh'},
    '173': {'district': 'Sirmaur / Solan', 'state': 'Himachal Pradesh'},
    '174': {'district': 'Bilaspur', 'state': 'Himachal Pradesh'},
    '175': {'district': 'Mandi / Kullu', 'state': 'Himachal Pradesh'},
    '176': {'district': 'Kangra (Dharamshala)', 'state': 'Himachal Pradesh'},
    '177': {'district': 'Hamirpur', 'state': 'Himachal Pradesh'},

    // Jammu & Kashmir and Ladakh
    '180': {'district': 'Jammu', 'state': 'Jammu & Kashmir'},
    '181': {'district': 'Samba / RS Pura', 'state': 'Jammu & Kashmir'},
    '182': {'district': 'Udhampur / Reasi', 'state': 'Jammu & Kashmir'},
    '184': {'district': 'Kathua', 'state': 'Jammu & Kashmir'},
    '185': {'district': 'Rajouri / Poonch', 'state': 'Jammu & Kashmir'},
    '190': {'district': 'Srinagar / Ganderbal', 'state': 'Jammu & Kashmir'},
    '191': {'district': 'Badgam', 'state': 'Jammu & Kashmir'},
    '192': {'district': 'Anantnag / Pulwama', 'state': 'Jammu & Kashmir'},
    '193': {'district': 'Baramulla', 'state': 'Jammu & Kashmir'},
    '194': {'district': 'Leh', 'state': 'Ladakh'},

    // Uttar Pradesh & Uttarakhand
    '201': {'district': 'Ghaziabad / Gautam Buddha Nagar (Noida)', 'state': 'Uttar Pradesh'},
    '202': {'district': 'Aligarh', 'state': 'Uttar Pradesh'},
    '203': {'district': 'Bulandshahr', 'state': 'Uttar Pradesh'},
    '204': {'district': 'Hathras', 'state': 'Uttar Pradesh'},
    '205': {'district': 'Mainpuri', 'state': 'Uttar Pradesh'},
    '206': {'district': 'Etawah', 'state': 'Uttar Pradesh'},
    '207': {'district': 'Etah', 'state': 'Uttar Pradesh'},
    '208': {'district': 'Kanpur Nagar', 'state': 'Uttar Pradesh'},
    '209': {'district': 'Kanpur Dehat', 'state': 'Uttar Pradesh'},
    '210': {'district': 'Banda', 'state': 'Uttar Pradesh'},
    '211': {'district': 'Prayagraj (Allahabad)', 'state': 'Uttar Pradesh'},
    '212': {'district': 'Kaushambi / Fatehpur', 'state': 'Uttar Pradesh'},
    '221': {'district': 'Varanasi', 'state': 'Uttar Pradesh'},
    '222': {'district': 'Jaunpur', 'state': 'Uttar Pradesh'},
    '223': {'district': 'Azamgarh', 'state': 'Uttar Pradesh'},
    '224': {'district': 'Ayodhya (Faizabad)', 'state': 'Uttar Pradesh'},
    '225': {'district': 'Barabanki', 'state': 'Uttar Pradesh'},
    '226': {'district': 'Lucknow', 'state': 'Uttar Pradesh'},
    '227': {'district': 'Amethi', 'state': 'Uttar Pradesh'},
    '228': {'district': 'Sultanpur', 'state': 'Uttar Pradesh'},
    '230': {'district': 'Pratapgarh', 'state': 'Uttar Pradesh'},
    '231': {'district': 'Mirzapur', 'state': 'Uttar Pradesh'},
    '232': {'district': 'Chandauli', 'state': 'Uttar Pradesh'},
    '241': {'district': 'Hardoi', 'state': 'Uttar Pradesh'},
    '242': {'district': 'Shahjahanpur', 'state': 'Uttar Pradesh'},
    '243': {'district': 'Bareilly', 'state': 'Uttar Pradesh'},
    '244': {'district': 'Moradabad / Rampur', 'state': 'Uttar Pradesh'},
    '245': {'district': 'Hapur', 'state': 'Uttar Pradesh'},
    '246': {'district': 'Bijnor / Pauri Garhwal', 'state': 'Uttar Pradesh'},
    '247': {'district': 'Saharanpur', 'state': 'Uttar Pradesh'},
    '248': {'district': 'Dehradun', 'state': 'Uttarakhand'},
    '249': {'district': 'Haridwar / Rishikesh / Tehri', 'state': 'Uttarakhand'},
    '250': {'district': 'Meerut', 'state': 'Uttar Pradesh'},
    '251': {'district': 'Muzaffarnagar', 'state': 'Uttar Pradesh'},
    '261': {'district': 'Sitapur', 'state': 'Uttar Pradesh'},
    '262': {'district': 'Pilibhit / Lakhimpur Kheri', 'state': 'Uttar Pradesh'},
    '263': {'district': 'Nainital / Almora', 'state': 'Uttarakhand'},
    '271': {'district': 'Gonda', 'state': 'Uttar Pradesh'},
    '272': {'district': 'Basti', 'state': 'Uttar Pradesh'},
    '273': {'district': 'Gorakhpur', 'state': 'Uttar Pradesh'},
    '274': {'district': 'Deoria', 'state': 'Uttar Pradesh'},
    '281': {'district': 'Mathura', 'state': 'Uttar Pradesh'},
    '282': {'district': 'Agra', 'state': 'Uttar Pradesh'},
    '283': {'district': 'Firozabad', 'state': 'Uttar Pradesh'},
    '284': {'district': 'Jhansi', 'state': 'Uttar Pradesh'},
    '285': {'district': 'Jalaun', 'state': 'Uttar Pradesh'},

    // Rajasthan
    '301': {'district': 'Alwar', 'state': 'Rajasthan'},
    '302': {'district': 'Jaipur', 'state': 'Rajasthan'},
    '303': {'district': 'Jaipur Rural / Dausa', 'state': 'Rajasthan'},
    '304': {'district': 'Tonk', 'state': 'Rajasthan'},
    '305': {'district': 'Ajmer', 'state': 'Rajasthan'},
    '311': {'district': 'Bhilwara', 'state': 'Rajasthan'},
    '312': {'district': 'Chittorgarh', 'state': 'Rajasthan'},
    '313': {'district': 'Udaipur', 'state': 'Rajasthan'},
    '314': {'district': 'Dungarpur', 'state': 'Rajasthan'},
    '321': {'district': 'Bharatpur', 'state': 'Rajasthan'},
    '322': {'district': 'Sawai Madhopur', 'state': 'Rajasthan'},
    '324': {'district': 'Kota', 'state': 'Rajasthan'},
    '325': {'district': 'Baran', 'state': 'Rajasthan'},
    '326': {'district': 'Jhalawar', 'state': 'Rajasthan'},
    '331': {'district': 'Churu', 'state': 'Rajasthan'},
    '332': {'district': 'Sikar', 'state': 'Rajasthan'},
    '333': {'district': 'Jhunjhunu', 'state': 'Rajasthan'},
    '334': {'district': 'Bikaner', 'state': 'Rajasthan'},
    '335': {'district': 'Sri Ganganagar / Hanumangarh', 'state': 'Rajasthan'},
    '341': {'district': 'Nagaur', 'state': 'Rajasthan'},
    '342': {'district': 'Jodhpur', 'state': 'Rajasthan'},
    '343': {'district': 'Jalore', 'state': 'Rajasthan'},
    '344': {'district': 'Barmer', 'state': 'Rajasthan'},
    '345': {'district': 'Jaisalmer', 'state': 'Rajasthan'},

    // Gujarat, Daman & Diu, Dadra & Nagar Haveli
    '360': {'district': 'Rajkot', 'state': 'Gujarat'},
    '361': {'district': 'Jamnagar', 'state': 'Gujarat'},
    '362': {'district': 'Junagadh', 'state': 'Gujarat'},
    '363': {'district': 'Surendranagar', 'state': 'Gujarat'},
    '364': {'district': 'Bhavnagar', 'state': 'Gujarat'},
    '365': {'district': 'Amreli', 'state': 'Gujarat'},
    '370': {'district': 'Kutch (Bhuj)', 'state': 'Gujarat'},
    '380': {'district': 'Ahmedabad', 'state': 'Gujarat'},
    '382': {'district': 'Gandhinagar', 'state': 'Gujarat'},
    '383': {'district': 'Sabarkantha', 'state': 'Gujarat'},
    '384': {'district': 'Mehsana / Patan', 'state': 'Gujarat'},
    '385': {'district': 'Banaskantha', 'state': 'Gujarat'},
    '387': {'district': 'Kheda (Nadiad)', 'state': 'Gujarat'},
    '388': {'district': 'Anand', 'state': 'Gujarat'},
    '389': {'district': 'Panchmahal (Godhra)', 'state': 'Gujarat'},
    '390': {'district': 'Vadodara', 'state': 'Gujarat'},
    '391': {'district': 'Vadodara Rural / Chhota Udepur', 'state': 'Gujarat'},
    '392': {'district': 'Bharuch', 'state': 'Gujarat'},
    '393': {'district': 'Ankleshwar / Narmada', 'state': 'Gujarat'},
    '394': {'district': 'Surat Rural / Tapi', 'state': 'Gujarat'},
    '395': {'district': 'Surat City', 'state': 'Gujarat'},
    '396': {'district': 'Valsad / Daman / Dadra & Nagar Haveli', 'state': 'Gujarat'},

    // Maharashtra & Goa
    '400': {'district': 'Mumbai City / Mumbai Suburban', 'state': 'Maharashtra'},
    '401': {'district': 'Thane / Palghar', 'state': 'Maharashtra'},
    '402': {'district': 'Raigad', 'state': 'Maharashtra'},
    '403': {'district': 'North Goa / South Goa', 'state': 'Goa'},
    '410': {'district': 'Lonavala / Pune Rural', 'state': 'Maharashtra'},
    '411': {'district': 'Pune City', 'state': 'Maharashtra'},
    '412': {'district': 'Pune Rural', 'state': 'Maharashtra'},
    '413': {'district': 'Solapur', 'state': 'Maharashtra'},
    '414': {'district': 'Ahmednagar', 'state': 'Maharashtra'},
    '415': {'district': 'Satara / Ratnagiri', 'state': 'Maharashtra'},
    '416': {'district': 'Kolhapur / Sangli / Sindhudurg', 'state': 'Maharashtra'},
    '421': {'district': 'Kalyan / Dombivli / Thane', 'state': 'Maharashtra'},
    '422': {'district': 'Nashik', 'state': 'Maharashtra'},
    '423': {'district': 'Malegaon / Nashik Rural', 'state': 'Maharashtra'},
    '424': {'district': 'Dhule', 'state': 'Maharashtra'},
    '425': {'district': 'Jalgaon', 'state': 'Maharashtra'},
    '431': {'district': 'Chhatrapati Sambhajinagar (Aurangabad) / Jalna', 'state': 'Maharashtra'},
    '440': {'district': 'Nagpur City', 'state': 'Maharashtra'},
    '441': {'district': 'Nagpur Rural / Bhandara / Gondia', 'state': 'Maharashtra'},
    '442': {'district': 'Wardha / Chandrapur', 'state': 'Maharashtra'},
    '443': {'district': 'Buldhana', 'state': 'Maharashtra'},
    '444': {'district': 'Amravati / Akola', 'state': 'Maharashtra'},
    '445': {'district': 'Yavatmal', 'state': 'Maharashtra'},

    // Madhya Pradesh & Chhattisgarh
    '450': {'district': 'Khandwa / Burhanpur', 'state': 'Madhya Pradesh'},
    '451': {'district': 'Khargone', 'state': 'Madhya Pradesh'},
    '452': {'district': 'Indore City', 'state': 'Madhya Pradesh'},
    '453': {'district': 'Indore Rural / Dhar', 'state': 'Madhya Pradesh'},
    '454': {'district': 'Dhar', 'state': 'Madhya Pradesh'},
    '455': {'district': 'Dewas', 'state': 'Madhya Pradesh'},
    '456': {'district': 'Ujjain', 'state': 'Madhya Pradesh'},
    '457': {'district': 'Ratlam / Mandsaur', 'state': 'Madhya Pradesh'},
    '462': {'district': 'Bhopal', 'state': 'Madhya Pradesh'},
    '464': {'district': 'Vidisha', 'state': 'Madhya Pradesh'},
    '465': {'district': 'Shajapur / Rajgarh', 'state': 'Madhya Pradesh'},
    '466': {'district': 'Sehore', 'state': 'Madhya Pradesh'},
    '470': {'district': 'Sagar', 'state': 'Madhya Pradesh'},
    '471': {'district': 'Chhatarpur', 'state': 'Madhya Pradesh'},
    '472': {'district': 'Tikamgarh / Niwari', 'state': 'Madhya Pradesh'},
    '474': {'district': 'Gwalior', 'state': 'Madhya Pradesh'},
    '475': {'district': 'Datia', 'state': 'Madhya Pradesh'},
    '476': {'district': 'Morena', 'state': 'Madhya Pradesh'},
    '477': {'district': 'Bhind', 'state': 'Madhya Pradesh'},
    '480': {'district': 'Chhindwara', 'state': 'Madhya Pradesh'},
    '481': {'district': 'Balaghat / Seoni', 'state': 'Madhya Pradesh'},
    '482': {'district': 'Jabalpur', 'state': 'Madhya Pradesh'},
    '483': {'district': 'Katni', 'state': 'Madhya Pradesh'},
    '484': {'district': 'Shahdol', 'state': 'Madhya Pradesh'},
    '485': {'district': 'Satna', 'state': 'Madhya Pradesh'},
    '486': {'district': 'Rewa', 'state': 'Madhya Pradesh'},
    '490': {'district': 'Bhilai / Durg', 'state': 'Chhattisgarh'},
    '491': {'district': 'Rajnandgaon', 'state': 'Chhattisgarh'},
    '492': {'district': 'Raipur', 'state': 'Chhattisgarh'},
    '493': {'district': 'Mahasamund / Baloda Bazar', 'state': 'Chhattisgarh'},
    '494': {'district': 'Bastar (Jagdalpur)', 'state': 'Chhattisgarh'},
    '495': {'district': 'Bilaspur', 'state': 'Chhattisgarh'},
    '496': {'district': 'Raigarh', 'state': 'Chhattisgarh'},
    '497': {'district': 'Surguja (Ambikapur)', 'state': 'Chhattisgarh'},

    // Telangana & Andhra Pradesh
    '500': {'district': 'Hyderabad', 'state': 'Telangana'},
    '501': {'district': 'Ranga Reddy / Vikarabad', 'state': 'Telangana'},
    '502': {'district': 'Sangareddy / Medak', 'state': 'Telangana'},
    '503': {'district': 'Nizamabad', 'state': 'Telangana'},
    '504': {'district': 'Adilabad / Mancherial', 'state': 'Telangana'},
    '505': {'district': 'Karimnagar / Peddapalli', 'state': 'Telangana'},
    '506': {'district': 'Warangal / Hanamkonda', 'state': 'Telangana'},
    '507': {'district': 'Khammam', 'state': 'Telangana'},
    '508': {'district': 'Nalgonda / Suryapet', 'state': 'Telangana'},
    '509': {'district': 'Mahabubnagar', 'state': 'Telangana'},
    '515': {'district': 'Anantapur / Sri Sathya Sai', 'state': 'Andhra Pradesh'},
    '516': {'district': 'YSR Kadapa', 'state': 'Andhra Pradesh'},
    '517': {'district': 'Tirupati / Chittoor', 'state': 'Andhra Pradesh'},
    '518': {'district': 'Kurnool / Nandyal', 'state': 'Andhra Pradesh'},
    '520': {'district': 'Vijayawada (NTR)', 'state': 'Andhra Pradesh'},
    '521': {'district': 'Krishna (Machilipatnam)', 'state': 'Andhra Pradesh'},
    '522': {'district': 'Guntur', 'state': 'Andhra Pradesh'},
    '523': {'district': 'Prakasam (Ongole)', 'state': 'Andhra Pradesh'},
    '524': {'district': 'Nellore', 'state': 'Andhra Pradesh'},
    '530': {'district': 'Visakhapatnam', 'state': 'Andhra Pradesh'},
    '531': {'district': 'Anakapalli', 'state': 'Andhra Pradesh'},
    '532': {'district': 'Srikakulam', 'state': 'Andhra Pradesh'},
    '533': {'district': 'Kakinada / East Godavari', 'state': 'Andhra Pradesh'},
    '534': {'district': 'Eluru / West Godavari', 'state': 'Andhra Pradesh'},
    '535': {'district': 'Vizianagaram', 'state': 'Andhra Pradesh'},

    // Karnataka
    '560': {'district': 'Bengaluru Urban', 'state': 'Karnataka'},
    '561': {'district': 'Bengaluru Rural / Chikkaballapur', 'state': 'Karnataka'},
    '562': {'district': 'Ramanagara / Kanakapura', 'state': 'Karnataka'},
    '563': {'district': 'Kolar (KGF)', 'state': 'Karnataka'},
    '570': {'district': 'Mysuru', 'state': 'Karnataka'},
    '571': {'district': 'Mandya / Chamarajanagar / Kodagu', 'state': 'Karnataka'},
    '572': {'district': 'Tumakuru', 'state': 'Karnataka'},
    '573': {'district': 'Hassan', 'state': 'Karnataka'},
    '574': {'district': 'Dakshina Kannada (Puttur/Bantwal)', 'state': 'Karnataka'},
    '575': {'district': 'Mangaluru', 'state': 'Karnataka'},
    '576': {'district': 'Udupi / Kundapura', 'state': 'Karnataka'},
    '577': {'district': 'Shivamogga / Davanagere / Chikkamagaluru', 'state': 'Karnataka'},
    '580': {'district': 'Hubballi-Dharwad', 'state': 'Karnataka'},
    '581': {'district': 'Uttara Kannada (Karwar/Sirsi)', 'state': 'Karnataka'},
    '582': {'district': 'Gadag', 'state': 'Karnataka'},
    '583': {'district': 'Ballari / Vijayanagara', 'state': 'Karnataka'},
    '584': {'district': 'Raichur', 'state': 'Karnataka'},
    '585': {'district': 'Kalaburagi / Bidar / Yadgir', 'state': 'Karnataka'},
    '586': {'district': 'Vijayapura (Bijapur)', 'state': 'Karnataka'},
    '587': {'district': 'Bagalkote', 'state': 'Karnataka'},
    '590': {'district': 'Belagavi City', 'state': 'Karnataka'},
    '591': {'district': 'Belagavi Rural / Chikkodi', 'state': 'Karnataka'},

    // Tamil Nadu & Puducherry
    '600': {'district': 'Chennai', 'state': 'Tamil Nadu'},
    '601': {'district': 'Tiruvallur', 'state': 'Tamil Nadu'},
    '602': {'district': 'Kanchipuram', 'state': 'Tamil Nadu'},
    '603': {'district': 'Chengalpattu', 'state': 'Tamil Nadu'},
    '604': {'district': 'Villupuram', 'state': 'Tamil Nadu'},
    '605': {'district': 'Puducherry', 'state': 'Puducherry'},
    '606': {'district': 'Tiruvannamalai', 'state': 'Tamil Nadu'},
    '607': {'district': 'Cuddalore', 'state': 'Tamil Nadu'},
    '608': {'district': 'Chidambaram', 'state': 'Tamil Nadu'},
    '609': {'district': 'Mayiladuthurai', 'state': 'Tamil Nadu'},
    '610': {'district': 'Tiruvarur', 'state': 'Tamil Nadu'},
    '611': {'district': 'Nagapattinam', 'state': 'Tamil Nadu'},
    '612': {'district': 'Kumbakonam', 'state': 'Tamil Nadu'},
    '613': {'district': 'Thanjavur', 'state': 'Tamil Nadu'},
    '614': {'district': 'Pattukkottai', 'state': 'Tamil Nadu'},
    '620': {'district': 'Tiruchirappalli', 'state': 'Tamil Nadu'},
    '621': {'district': 'Perambalur / Ariyalur', 'state': 'Tamil Nadu'},
    '622': {'district': 'Pudukkottai', 'state': 'Tamil Nadu'},
    '623': {'district': 'Ramanathapuram', 'state': 'Tamil Nadu'},
    '624': {'district': 'Dindigul', 'state': 'Tamil Nadu'},
    '625': {'district': 'Madurai', 'state': 'Tamil Nadu'},
    '626': {'district': 'Virudhunagar / Sivakasi', 'state': 'Tamil Nadu'},
    '627': {'district': 'Tirunelveli', 'state': 'Tamil Nadu'},
    '628': {'district': 'Thoothukudi', 'state': 'Tamil Nadu'},
    '629': {'district': 'Kanniyakumari (Nagercoil)', 'state': 'Tamil Nadu'},
    '630': {'district': 'Sivaganga / Karaikudi', 'state': 'Tamil Nadu'},
    '632': {'district': 'Vellore / Ranipet', 'state': 'Tamil Nadu'},
    '635': {'district': 'Krishnagiri / Dharmapuri', 'state': 'Tamil Nadu'},
    '636': {'district': 'Salem', 'state': 'Tamil Nadu'},
    '637': {'district': 'Namakkal', 'state': 'Tamil Nadu'},
    '638': {'district': 'Erode', 'state': 'Tamil Nadu'},
    '641': {'district': 'Coimbatore', 'state': 'Tamil Nadu'},
    '642': {'district': 'Pollachi / Tiruppur Rural', 'state': 'Tamil Nadu'},
    '643': {'district': 'Nilgiris (Ooty)', 'state': 'Tamil Nadu'},

    // Kerala & Lakshadweep
    '670': {'district': 'Kannur', 'state': 'Kerala'},
    '671': {'district': 'Kasaragod', 'state': 'Kerala'},
    '673': {'district': 'Kozhikode / Wayanad', 'state': 'Kerala'},
    '676': {'district': 'Malappuram (Tirur/Manjeri)', 'state': 'Kerala'},
    '678': {'district': 'Palakkad', 'state': 'Kerala'},
    '679': {'district': 'Shoranur / Ottapalam', 'state': 'Kerala'},
    '680': {'district': 'Thrissur', 'state': 'Kerala'},
    '682': {'district': 'Kochi (Ernakulam)', 'state': 'Kerala'},
    '683': {'district': 'Aluva / Perumbavoor', 'state': 'Kerala'},
    '685': {'district': 'Idukki (Munnar/Thodupuzha)', 'state': 'Kerala'},
    '686': {'district': 'Kottayam', 'state': 'Kerala'},
    '688': {'district': 'Alappuzha', 'state': 'Kerala'},
    '689': {'district': 'Pathanamthitta (Tiruvalla)', 'state': 'Kerala'},
    '690': {'district': 'Kayamkulam / Mavelikkara', 'state': 'Kerala'},
    '691': {'district': 'Kollam', 'state': 'Kerala'},
    '695': {'district': 'Thiruvananthapuram', 'state': 'Kerala'},
    '682555': {'district': 'Kavaratti', 'state': 'Lakshadweep'},

    // West Bengal, Sikkim & A&N
    '700': {'district': 'Kolkata', 'state': 'West Bengal'},
    '711': {'district': 'Howrah', 'state': 'West Bengal'},
    '712': {'district': 'Hooghly', 'state': 'West Bengal'},
    '713': {'district': 'Paschim Bardhaman (Durgapur/Asansol)', 'state': 'West Bengal'},
    '721': {'district': 'Paschim Medinipur / Jhargram', 'state': 'West Bengal'},
    '722': {'district': 'Bankura', 'state': 'West Bengal'},
    '723': {'district': 'Purulia', 'state': 'West Bengal'},
    '731': {'district': 'Birbhum', 'state': 'West Bengal'},
    '732': {'district': 'Malda', 'state': 'West Bengal'},
    '733': {'district': 'Uttar Dinajpur / Dakshin Dinajpur', 'state': 'West Bengal'},
    '734': {'district': 'Darjeeling / Siliguri', 'state': 'West Bengal'},
    '735': {'district': 'Jalpaiguri / Alipurduar', 'state': 'West Bengal'},
    '736': {'district': 'Cooch Behar', 'state': 'West Bengal'},
    '737': {'district': 'East Sikkim (Gangtok) / South Sikkim', 'state': 'Sikkim'},
    '741': {'district': 'Nadia', 'state': 'West Bengal'},
    '742': {'district': 'Murshidabad', 'state': 'West Bengal'},
    '743': {'district': 'North 24 Parganas / South 24 Parganas', 'state': 'West Bengal'},
    '744': {'district': 'South Andaman (Port Blair) / Nicobar', 'state': 'Andaman & Nicobar Islands'},

    // Odisha
    '751': {'district': 'Khurda (Bhubaneswar)', 'state': 'Odisha'},
    '752': {'district': 'Puri', 'state': 'Odisha'},
    '753': {'district': 'Cuttack', 'state': 'Odisha'},
    '754': {'district': 'Jagatsinghpur / Kendrapara', 'state': 'Odisha'},
    '755': {'district': 'Jajpur', 'state': 'Odisha'},
    '756': {'district': 'Balasore / Bhadrak', 'state': 'Odisha'},
    '757': {'district': 'Mayurbhanj (Baripada)', 'state': 'Odisha'},
    '758': {'district': 'Keonjhar', 'state': 'Odisha'},
    '759': {'district': 'Dhenkanal / Angul', 'state': 'Odisha'},
    '760': {'district': 'Ganjam (Berhampur)', 'state': 'Odisha'},
    '761': {'district': 'Gajapati', 'state': 'Odisha'},
    '762': {'district': 'Kandhamal', 'state': 'Odisha'},
    '763': {'district': 'Boudh', 'state': 'Odisha'},
    '764': {'district': 'Koraput', 'state': 'Odisha'},
    '765': {'district': 'Rayagada', 'state': 'Odisha'},
    '766': {'district': 'Kalahandi', 'state': 'Odisha'},
    '767': {'district': 'Balangir', 'state': 'Odisha'},
    '768': {'district': 'Sambalpur / Bargarh', 'state': 'Odisha'},
    '769': {'district': 'Sundargarh (Rourkela)', 'state': 'Odisha'},

    // Assam & North East
    '781': {'district': 'Kamrup Metropolitan (Guwahati)', 'state': 'Assam'},
    '782': {'district': 'Nagaon / Morigaon', 'state': 'Assam'},
    '783': {'district': 'Goalpara / Dhubri / Bongaigaon', 'state': 'Assam'},
    '784': {'district': 'Sonitpur (Tezpur) / Darrang', 'state': 'Assam'},
    '785': {'district': 'Jorhat / Golaghat / Sivasagar', 'state': 'Assam'},
    '786': {'district': 'Dibrugarh / Tinsukia', 'state': 'Assam'},
    '787': {'district': 'Lakhimpur / Dhemaji', 'state': 'Assam'},
    '788': {'district': 'Cachar (Silchar) / Karimganj', 'state': 'Assam'},
    '790': {'district': 'Tawang / West Kameng', 'state': 'Arunachal Pradesh'},
    '791': {'district': 'Papum Pare (Itanagar)', 'state': 'Arunachal Pradesh'},
    '792': {'district': 'East Siang (Pasighat)', 'state': 'Arunachal Pradesh'},
    '793': {'district': 'East Khasi Hills (Shillong)', 'state': 'Meghalaya'},
    '794': {'district': 'West Garo Hills (Tura)', 'state': 'Meghalaya'},
    '795': {'district': 'Imphal West / Imphal East', 'state': 'Manipur'},
    '796': {'district': 'Aizawl', 'state': 'Mizoram'},
    '797': {'district': 'Kohima / Dimapur', 'state': 'Nagaland'},
    '798': {'district': 'Mokokchung', 'state': 'Nagaland'},
    '799': {'district': 'West Tripura (Agartala)', 'state': 'Tripura'},

    // Bihar & Jharkhand
    '800': {'district': 'Patna Urban', 'state': 'Bihar'},
    '801': {'district': 'Patna Rural (Danapur/Phulwari)', 'state': 'Bihar'},
    '802': {'district': 'Bhojpur (Ara) / Buxar', 'state': 'Bihar'},
    '803': {'district': 'Nalanda (Bihar Sharif)', 'state': 'Bihar'},
    '804': {'district': 'Jehanabad / Arwal', 'state': 'Bihar'},
    '805': {'district': 'Nawada', 'state': 'Bihar'},
    '811': {'district': 'Munger / Lakhisarai', 'state': 'Bihar'},
    '812': {'district': 'Bhagalpur', 'state': 'Bihar'},
    '813': {'district': 'Banka', 'state': 'Bihar'},
    '814': {'district': 'Deoghar / Dumka', 'state': 'Jharkhand'},
    '815': {'district': 'Giridih', 'state': 'Jharkhand'},
    '816': {'district': 'Sahibganj / Pakur', 'state': 'Jharkhand'},
    '821': {'district': 'Rohtas (Sasaram) / Kaimur', 'state': 'Bihar'},
    '822': {'district': 'Palamu (Daltonganj)', 'state': 'Jharkhand'},
    '823': {'district': 'Gaya', 'state': 'Bihar'},
    '824': {'district': 'Aurangabad', 'state': 'Bihar'},
    '825': {'district': 'Hazaribagh / Ramgarh', 'state': 'Jharkhand'},
    '826': {'district': 'Dhanbad', 'state': 'Jharkhand'},
    '827': {'district': 'Bokaro', 'state': 'Jharkhand'},
    '828': {'district': 'Dhanbad Rural', 'state': 'Jharkhand'},
    '829': {'district': 'Bokaro Rural / Ramgarh', 'state': 'Jharkhand'},
    '831': {'district': 'East Singhbhum (Jamshedpur)', 'state': 'Jharkhand'},
    '832': {'district': 'Seraikela Kharsawan', 'state': 'Jharkhand'},
    '833': {'district': 'West Singhbhum (Chaibasa)', 'state': 'Jharkhand'},
    '834': {'district': 'Ranchi', 'state': 'Jharkhand'},
    '835': {'district': 'Ranchi Rural / Khunti / Gumla', 'state': 'Jharkhand'},
    '841': {'district': 'Saran (Chapra) / Siwan / Gopalganj', 'state': 'Bihar'},
    '842': {'district': 'Muzaffarpur', 'state': 'Bihar'},
    '843': {'district': 'Sitamarhi / Sheohar', 'state': 'Bihar'},
    '844': {'district': 'Vaishali (Hajipur)', 'state': 'Bihar'},
    '845': {'district': 'East Champaran (Motihari) / West Champaran (Bettiah)', 'state': 'Bihar'},
    '846': {'district': 'Darbhanga', 'state': 'Bihar'},
    '847': {'district': 'Madhubani', 'state': 'Bihar'},
    '848': {'district': 'Samastipur', 'state': 'Bihar'},
    '851': {'district': 'Begusarai', 'state': 'Bihar'},
    '852': {'district': 'Saharsa / Madhepura / Supaul', 'state': 'Bihar'},
    '853': {'district': 'Khagaria', 'state': 'Bihar'},
    '854': {'district': 'Purnia / Katihar / Araria / Kishanganj', 'state': 'Bihar'},
    '855': {'district': 'Kishanganj', 'state': 'Bihar'},
  };
}
