name: bharat_fx
description: "The Ultimate Indian Localization & Input Toolkit for Flutter. Indian currency formatter (Lakh/Crore & words), offline PIN code address resolver, vernacular phonetic keyboard, vehicle plate validator, and Indian ID validators (Aadhaar, PAN, UPI, GSTIN)."
version: 1.0.0
homepage: https://github.com/codernta/bharat_fx
repository: https://github.com/codernta/bharat_fx
issue_tracker: https://github.com/codernta/bharat_fx/issues

topics:
  - localization
  - india
  - currency
  - input-validation
  - forms

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
